/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.congnghephanmem.frame;

import com.congnghephanmem.DAO.HokhauDAO;
import com.congnghephanmem.DAO.NhankhauDAO;
import com.congnghephanmem.model.Hokhau;
import com.congnghephanmem.model.Nhankhau;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vu
 */
public class ChitietFR extends javax.swing.JFrame {

    /**
     * Creates new form ChitietFR
     */
    
    NhankhauDAO nhankhaudao= new NhankhauDAO();
    List<Nhankhau> nhankhau= nhankhaudao.xuatnhankhau();
    HokhauDAO hokhaudao=new HokhauDAO();
    Hokhau hk=new Hokhau();
    Nhankhau nk= new Nhankhau();
    SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
    int i=0;
    
    private void update(int i){
        txtmadinhdanh.setText(nhankhau.get(i).getMadinhdanh());
        txthoten.setText(nhankhau.get(i).getHoten());
        txtbidanh.setText(nhankhau.get(i).getBidanh());
        txtngaysinh.setText(fmt.format(nhankhau.get(i).getNgaysinh()));
        txtnoisinh.setText(nhankhau.get(i).getNoisinh());
        txtnguyenquan.setText(nhankhau.get(i).getNguyenquan());
        txtdantoc.setText(nhankhau.get(i).getDantoc());
        txtnghenghiep.setText(nhankhau.get(i).getNghenghiep());
        txtnoilamviec.setText(nhankhau.get(i).getNoilamviec());
        txtcmnd.setText(nhankhau.get(i).getCmnd());
        txtngaycap.setText(fmt.format(nhankhau.get(i).getNgaycap()));
        txtnoicap.setText(nhankhau.get(i).getNoicap());
        txtquanhe.setText(nhankhau.get(i).getQuanhe());
        txtdiachicu.setText(nhankhau.get(i).getDiachicu());
        txtngaydkthuongtru.setText(fmt.format(nhankhau.get(i).getNgaydkthuongtru()));
        txtghichu1.setText(nhankhau.get(i).getGhichu());
        if(nhankhau.get(i).getGhichu().equals("Chuyển đi nơi khác")){
            jLabel22.setVisible(true);
            jLabel23.setVisible(true);
            txtngaychuyendi.setVisible(true);
            txtnoichuyen.setVisible(true);
            txtngaychuyendi.setText(fmt.format(nhankhau.get(i).getNgaychuyendi()));
            txtnoichuyen.setText(nhankhau.get(i).getNoichuyen());
        }else{
            jLabel22.setVisible(false);
            jLabel23.setVisible(false);
            txtngaychuyendi.setVisible(false);
            txtnoichuyen.setVisible(false);
        }
    }
    
    private void setLock(){
        txthoten.setEditable(false);
        txtbidanh.setEditable(false);
        txtngaysinh.setEditable(false);
        txtnoisinh.setEditable(false);
        txtnguyenquan.setEditable(false);
        txtdantoc.setEditable(false);
        txtnghenghiep.setEditable(false);
        txtnoilamviec.setEditable(false);
        txtcmnd.setEditable(false);
        txtngaycap.setEditable(false);
        txtnoicap.setEditable(false);
        txtquanhe.setEditable(false);
        txtdiachicu.setEditable(false);
        txtngaydkthuongtru.setEditable(false);
        txtghichu1.setEditable(false);
        txtngaychuyendi.setEditable(false);
        txtnoichuyen.setEditable(false);
    }
    
    private void setUnlock(){
        txthoten.setEditable(true);
        txtbidanh.setEditable(true);
        txtngaysinh.setEditable(true);
        txtnoisinh.setEditable(true);
        txtnguyenquan.setEditable(true);
        txtdantoc.setEditable(true);
        txtnghenghiep.setEditable(true);
        txtnoilamviec.setEditable(true);
        txtcmnd.setEditable(true);
        txtngaycap.setEditable(true);
        txtnoicap.setEditable(true);
        txtquanhe.setEditable(true);
        txtdiachicu.setEditable(true);
        txtngaydkthuongtru.setEditable(true);
        txtghichu1.setEditable(true);
        txtngaychuyendi.setEditable(true);
        txtnoichuyen.setEditable(true);
    }
    
    public ChitietFR() {
        initComponents();
        txtsohokhau.setText(nhankhaudao.id);
        txttenchuho.setText(nhankhaudao.ten);
        txtsohokhau.setEditable(false);
        txttenchuho.setEditable(false);
        setLock();
        xacnhanbutton.setVisible(false);
        update(i);
        jLabel18.setVisible(false);
        ghichucombobox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtghichu = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtngaydkthuongtru = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtmadinhdanh = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtbidanh = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtnoisinh = new javax.swing.JTextField();
        txtnguyenquan = new javax.swing.JTextField();
        txtdantoc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtnghenghiep = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnoilamviec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcmnd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtngaycap = new javax.swing.JTextField();
        txtnoicap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtquanhe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdiachicu = new javax.swing.JTextField();
        saubutton = new javax.swing.JButton();
        truocbutton = new javax.swing.JButton();
        xoabutton = new javax.swing.JButton();
        suabutton = new javax.swing.JButton();
        txtghichu1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        xacnhanbutton = new javax.swing.JButton();
        txtngaychuyendi = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtnoichuyen = new javax.swing.JTextField();
        quaylaibutton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        ghichucombobox = new javax.swing.JComboBox<>();
        txtsohokhau = new javax.swing.JTextField();
        txttenchuho = new javax.swing.JTextField();

        jLabel20.setText("Ghi chú khác:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Nghề nghiệp:");

        txtngaydkthuongtru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaydkthuongtruActionPerformed(evt);
            }
        });

        jLabel9.setText("Nơi làm việc:");

        jLabel10.setText("Số CMND:");

        jLabel11.setText("Ngày cấp:");

        jLabel12.setText("Nơi cấp:");

        jLabel16.setText("Số hộ khẩu:");

        jLabel13.setText("Quan hệ với chủ hộ:");

        jLabel14.setText("Địa chỉ thường trú cũ:");

        jLabel15.setText("Ngày đăng kí thường trú:");

        jLabel17.setText("Chủ hộ:");

        txtnoisinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoisinhActionPerformed(evt);
            }
        });

        txtnguyenquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnguyenquanActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã định danh:");

        jLabel2.setText("Họ tên:");

        jLabel3.setText("Bí danh:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("Nơi sinh:");

        jLabel6.setText("Nguyên quán:");

        txtquanhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquanheActionPerformed(evt);
            }
        });

        jLabel7.setText("Dân tộc:");

        saubutton.setText("Trang sau");
        saubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saubuttonActionPerformed(evt);
            }
        });

        truocbutton.setText("Trang trước");
        truocbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truocbuttonActionPerformed(evt);
            }
        });

        xoabutton.setText("Xóa");
        xoabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabuttonActionPerformed(evt);
            }
        });

        suabutton.setText("Sửa");
        suabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suabuttonActionPerformed(evt);
            }
        });

        jLabel21.setText("Ghi chú:");

        xacnhanbutton.setText("Xác nhận");
        xacnhanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanbuttonActionPerformed(evt);
            }
        });

        jLabel22.setText("Ngày chuyển đi:");

        jLabel23.setText("Nơi chuyển:");

        quaylaibutton.setText("Quay lại");
        quaylaibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylaibuttonActionPerformed(evt);
            }
        });

        jLabel18.setText("Nội dung ghi chú:");

        ghichucombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuyển đi nơi khác", "Qua đời", "Khác", "Không có" }));
        ghichucombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghichucomboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnguyenquan)
                                    .addComponent(txtdantoc)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnoisinh))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmadinhdanh)
                                    .addComponent(txthoten)
                                    .addComponent(txtbidanh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel10))
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcmnd)
                                    .addComponent(txtnghenghiep)
                                    .addComponent(txtnoilamviec)
                                    .addComponent(txtquanhe, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnoicap)
                                    .addComponent(txtngaycap, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtghichu1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdiachicu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtngaychuyendi)
                                    .addComponent(txtnoichuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xacnhanbutton)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtngaydkthuongtru, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ghichucombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(txtsohokhau, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttenchuho, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(truocbutton)
                .addGap(18, 18, 18)
                .addComponent(saubutton)
                .addGap(31, 31, 31)
                .addComponent(xoabutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suabutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quaylaibutton)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jLabel16)
                    .addGap(171, 171, 171)
                    .addComponent(jLabel17)
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsohokhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenchuho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmadinhdanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtquanhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtnghenghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtbidanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnoilamviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(txtcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnoisinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtngaycap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtnguyenquan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnoicap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdiachicu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtngaydkthuongtru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtghichu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel18)
                    .addComponent(ghichucombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngaychuyendi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnoichuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xacnhanbutton)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saubutton)
                    .addComponent(truocbutton)
                    .addComponent(xoabutton)
                    .addComponent(suabutton)
                    .addComponent(quaylaibutton))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addContainerGap(464, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtngaydkthuongtruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaydkthuongtruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaydkthuongtruActionPerformed

    private void txtnoisinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoisinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoisinhActionPerformed

    private void txtnguyenquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnguyenquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnguyenquanActionPerformed

    private void txtquanheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquanheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquanheActionPerformed

    private void saubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saubuttonActionPerformed
        // TODO add your handling code here:
        if(i<nhankhau.size()-1){
            i=i+1;
            update(i);
        }
    }//GEN-LAST:event_saubuttonActionPerformed

    private void truocbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truocbuttonActionPerformed
        // TODO add your handling code here:
        if(i>0){
            i=i-1;
            update(i);
        }
    }//GEN-LAST:event_truocbuttonActionPerformed

    private void xoabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabuttonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa dữ liệu","CẢNH BÁO",JOptionPane.YES_NO_OPTION);
            if(confirm==JOptionPane.YES_OPTION){
                nhankhaudao.xoanhankhau(txtmadinhdanh.getText());
                JOptionPane.showMessageDialog(this," Đã xoá ! ");
            }
            else{
                JOptionPane.showMessageDialog(this," Xoá thất bại ! ");
            }
            nhankhau= nhankhaudao.xuatnhankhau();
            if(nhankhau.size()==0){
                JOptionPane.showMessageDialog(this,"Hộ khẩu chưa có nhân khẩu !");
                this.dispose();
            }
    }//GEN-LAST:event_xoabuttonActionPerformed

    private void suabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suabuttonActionPerformed
        // TODO add your handling code here:
        setUnlock();
        xacnhanbutton.setVisible(true);
        truocbutton.setEnabled(false);
        saubutton.setEnabled(false);
        xoabutton.setEnabled(false);
        jLabel18.setVisible(true);
        ghichucombobox.setVisible(true);
    }//GEN-LAST:event_suabuttonActionPerformed

    private void quaylaibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylaibuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quaylaibuttonActionPerformed

    private void xacnhanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanbuttonActionPerformed
        // TODO add your handling code here:  
        nk.setMadinhdanh(txtmadinhdanh.getText());
        nk.setHoten(txthoten.getText());
        nk.setBidanh(txtbidanh.getText());
        try {
            nk.setNgaysinh(fmt.parse(txtngaysinh.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(ChitietFR.class.getName()).log(Level.SEVERE, null, ex);
        }
        nk.setNoisinh(txtnoisinh.getText());
        nk.setNguyenquan(txtnguyenquan.getText());
        nk.setDantoc(txtdantoc.getText());
        nk.setQuanhe(txtquanhe.getText());
        nk.setNghenghiep(txtnghenghiep.getText());
        nk.setNoilamviec(txtnoilamviec.getText());
        nk.setCmnd(txtcmnd.getText());
        try {
            nk.setNgaycap(fmt.parse(txtngaycap.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(ChitietFR.class.getName()).log(Level.SEVERE, null, ex);
        }
        nk.setNoicap(txtnoicap.getText());
        nk.setDiachicu(txtdiachicu.getText());
        try {
            nk.setNgaydkthuongtru(fmt.parse(txtngaydkthuongtru.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(ChitietFR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String selectedRow=(String) ghichucombobox.getSelectedItem();
        if(selectedRow.equals("Chuyển đi nơi khác")){
            nk.setGhichu(txtghichu1.getText());
            nk.setNoichuyen(txtnoichuyen.getText());
            try {
                nk.setNgaychuyendi(fmt.parse(txtngaychuyendi.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(ChitietFR.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(selectedRow.equals("Khác")){
            nk.setGhichu(txtghichu1.getText());
            nk.setNoichuyen("");
            try {
                    nk.setNgaychuyendi(fmt.parse("00/00/0000"));
                } catch (ParseException ex) {
                    Logger.getLogger(ChitietFR.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else if(selectedRow.equals("Qua đời")){
            nk.setGhichu(txtghichu1.getText());
            nk.setNoichuyen("");
            try {
                    nk.setNgaychuyendi(fmt.parse("00/00/0000"));
                } catch (ParseException ex) {
                    Logger.getLogger(ChitietFR.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else if(selectedRow.equals("Không có")){
            nk.setGhichu("");
            nk.setNoichuyen("");
            try {
                    nk.setNgaychuyendi(fmt.parse("00/00/0000"));
                } catch (ParseException ex) {
                    Logger.getLogger(ChitietFR.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        if (nhankhaudao.capnhatnhankhau(nk)==1){
            JOptionPane.showMessageDialog(this," Đã sửa ! ");
        }else {
            JOptionPane.showMessageDialog(this, " Sửa thất bại ! ");
        }
        setLock();
        xacnhanbutton.setVisible(false);
        truocbutton.setEnabled(true);
        saubutton.setEnabled(true);
        xoabutton.setEnabled(true);
    }//GEN-LAST:event_xacnhanbuttonActionPerformed

    private void ghichucomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghichucomboboxActionPerformed
        // TODO add your handling code here:
        String selectedRow = (String)ghichucombobox.getSelectedItem();
        if(selectedRow.equals("Chuyển đi nơi khác")){
            txtghichu1.setText("Chuyển đi nơi khác");
            jLabel22.setVisible(true);
            jLabel23.setVisible(true);
            txtngaychuyendi.setVisible(true);
            txtnoichuyen.setVisible(true); 
        }else if(selectedRow.equals("Khác")){
            jLabel22.setVisible(false);
            jLabel23.setVisible(false);
            txtngaychuyendi.setVisible(false);
            txtnoichuyen.setVisible(false);
        }else if((selectedRow.equals("Qua đời"))){
            jLabel22.setVisible(false);
            jLabel23.setVisible(false);
            txtghichu1.setText("Qua đời");
            txtngaychuyendi.setVisible(false);
            txtnoichuyen.setVisible(false);
        }else if((selectedRow.equals("Không có"))){
            jLabel22.setVisible(false);
            jLabel23.setVisible(false);
            txtghichu1.setVisible(false);
            txtngaychuyendi.setVisible(false);
            txtnoichuyen.setVisible(false);
        }
    }//GEN-LAST:event_ghichucomboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChitietFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChitietFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChitietFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChitietFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChitietFR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ghichucombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton quaylaibutton;
    private javax.swing.JButton saubutton;
    private javax.swing.JButton suabutton;
    private javax.swing.JButton truocbutton;
    private javax.swing.JTextField txtbidanh;
    private javax.swing.JTextField txtcmnd;
    private javax.swing.JTextField txtdantoc;
    private javax.swing.JTextField txtdiachicu;
    private javax.swing.JTextField txtghichu;
    private javax.swing.JTextField txtghichu1;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmadinhdanh;
    private javax.swing.JTextField txtngaycap;
    private javax.swing.JTextField txtngaychuyendi;
    private javax.swing.JTextField txtngaydkthuongtru;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtnghenghiep;
    private javax.swing.JTextField txtnguyenquan;
    private javax.swing.JTextField txtnoicap;
    private javax.swing.JTextField txtnoichuyen;
    private javax.swing.JTextField txtnoilamviec;
    private javax.swing.JTextField txtnoisinh;
    private javax.swing.JTextField txtquanhe;
    private javax.swing.JTextField txtsohokhau;
    private javax.swing.JTextField txttenchuho;
    private javax.swing.JButton xacnhanbutton;
    private javax.swing.JButton xoabutton;
    // End of variables declaration//GEN-END:variables
}
