/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.congnghephanmem.frame;

import com.congnghephanmem.DAO.HokhauDAO;
import com.congnghephanmem.DAO.NhankhauDAO;
import com.congnghephanmem.model.Hokhau;
import com.congnghephanmem.model.Nhankhau;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vu
 */
public class HokhauFR extends javax.swing.JFrame {

    /**
     * Creates new form HokhauFR
     */
    
    List<Hokhau> hokhau;
    HokhauDAO hokhaudao = new HokhauDAO();
    Hokhau hk = new Hokhau();
    NhankhauDAO nhankhaudao = new NhankhauDAO();

    private void setNULL(){
        txtsohokhau.setText("");
        txttenchuho.setText("");
        txtdiachi.setText("");
    }
    
    private void update_table(){
        DefaultTableModel df = (DefaultTableModel)HokhauTable.getModel();
        df.setRowCount(0);
        hokhau=hokhaudao.xuathokhau();
        for(Hokhau i: hokhau){
            df.addRow(new Object[]{i.getSohokhau(), i.getHotenchuho(), i.getDiachi()});
        }
        txtsohokhau.requestFocus();
    }
    
    public HokhauFR() {
        initComponents();
        update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsohokhau = new javax.swing.JTextField();
        txttenchuho = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        HokhauTable = new javax.swing.JTable();
        thembutton = new javax.swing.JButton();
        xoatable = new javax.swing.JButton();
        suabutton = new javax.swing.JButton();
        themnkbutton = new javax.swing.JButton();
        chitietbutton = new javax.swing.JButton();
        tachhokhaubutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Số hộ khẩu:");

        jLabel2.setText("Tên chủ hộ:");

        jLabel3.setText("Địa chỉ:");

        HokhauTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Số hộ khẩu", "Tên chủ hộ", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HokhauTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HokhauTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(HokhauTable);

        thembutton.setText("Thêm");
        thembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thembuttonActionPerformed(evt);
            }
        });

        xoatable.setText("Xóa");
        xoatable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoatableActionPerformed(evt);
            }
        });

        suabutton.setText("Sửa");
        suabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suabuttonActionPerformed(evt);
            }
        });

        themnkbutton.setText("Thêm nhân khẩu");
        themnkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themnkbuttonActionPerformed(evt);
            }
        });

        chitietbutton.setText("Xem chi tiết");
        chitietbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chitietbuttonActionPerformed(evt);
            }
        });

        tachhokhaubutton.setText("Tách hộ khẩu");
        tachhokhaubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tachhokhaubuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsohokhau)
                                    .addComponent(txttenchuho)
                                    .addComponent(txtdiachi, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(thembutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xoatable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(suabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tachhokhaubutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(themnkbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(chitietbutton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtsohokhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thembutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenchuho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoatable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suabutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themnkbutton)
                    .addComponent(chitietbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tachhokhaubutton)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thembuttonActionPerformed
        // TODO add your handling code here:
        try{
            hk.setSohokhau(txtsohokhau.getText());
            hk.setHotenchuho(txttenchuho.getText());
            hk.setDiachi(txtdiachi.getText());
            if (hokhaudao.themhokhau(hk) == 1) {
                JOptionPane.showMessageDialog(this," Đã thêm ! ");
            } else {
                JOptionPane.showMessageDialog(this, " Thêm thất bại ! ");
            }
            setNULL();
            update_table();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, " Thêm thất bại ! ");
        }
    }//GEN-LAST:event_thembuttonActionPerformed

    private void xoatableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoatableActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel df = (DefaultTableModel) HokhauTable.getModel();
            int index = HokhauTable.getSelectedRow();
            String id = (String) df.getValueAt(index, 0);
            int confirm = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa dữ liệu","CẢNH BÁO",JOptionPane.YES_NO_OPTION);
            if(confirm==JOptionPane.YES_OPTION){
                hokhaudao.xoahokhau(id);
                JOptionPane.showMessageDialog(this," Đã xoá ! ");
                update_table();
                setNULL();
            }
            else{
                JOptionPane.showMessageDialog(this," Xoá thất bại ! ");
             }
        }
        catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this," Bạn chưa chọn mục để xóa ");
        }
    }//GEN-LAST:event_xoatableActionPerformed

    private void HokhauTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HokhauTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel df=(DefaultTableModel) HokhauTable.getModel();
        int index=HokhauTable.getSelectedRow();
        txtsohokhau.setText((String)df.getValueAt(index, 0));
        txttenchuho.setText((String)df.getValueAt(index, 1));
        txtdiachi.setText((String)df.getValueAt(index, 2));
        nhankhaudao.setId((String)df.getValueAt(index, 0));
        nhankhaudao.setTen((String)df.getValueAt(index, 1));
    }//GEN-LAST:event_HokhauTableMouseClicked

    private void suabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suabuttonActionPerformed
        // TODO add your handling code here:
        hk.setSohokhau(txtsohokhau.getText());
        hk.setHotenchuho(txttenchuho.getText());
        hk.setDiachi(txtdiachi.getText());
        
        if(hokhaudao.capnhathokhau(hk)==1){
            JOptionPane.showMessageDialog(this," Đã sửa ! ");
        }else {
            JOptionPane.showMessageDialog(this, " Sửa thất bại ! ");
        }
        update_table();
        setNULL();
    }//GEN-LAST:event_suabuttonActionPerformed

    private void themnkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themnkbuttonActionPerformed
        // TODO add your handling code here:
        new ThemNhankhauFR().setVisible(true);
    }//GEN-LAST:event_themnkbuttonActionPerformed

    private void chitietbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chitietbuttonActionPerformed
        // TODO add your handling code here:
        List<Nhankhau> nhankhau=nhankhaudao.xuatnhankhau();
        if(nhankhau.size()==0){
            JOptionPane.showMessageDialog(this," Hộ khẩu chưa có nhân khẩu !");
        }else{
            new ChitietFR().setVisible(true);
        }
    }//GEN-LAST:event_chitietbuttonActionPerformed

    private void tachhokhaubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tachhokhaubuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tachhokhaubuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HokhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HokhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HokhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HokhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HokhauFR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HokhauTable;
    private javax.swing.JButton chitietbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton suabutton;
    private javax.swing.JButton tachhokhaubutton;
    private javax.swing.JButton thembutton;
    private javax.swing.JButton themnkbutton;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtsohokhau;
    private javax.swing.JTextField txttenchuho;
    private javax.swing.JButton xoatable;
    // End of variables declaration//GEN-END:variables
}
