/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.congnghephanmem.frame;

import com.congnghephanmem.DAO.HokhauDAO;
import com.congnghephanmem.DAO.NhankhauDAO;
import com.congnghephanmem.model.Hokhau;
import com.congnghephanmem.model.Nhankhau;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vu
 */
public class ThemNhankhauFR extends javax.swing.JFrame {

    /**
     * Creates new form NhankhauFR
     */
    
    List<Nhankhau> nhankhau= new ArrayList<Nhankhau>();
    NhankhauDAO nhankhaudao= new NhankhauDAO();
    HokhauDAO hokhaudao=new HokhauDAO();
    Hokhau hk=new Hokhau();
    Nhankhau nk= new Nhankhau();
    SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
    
    private void setNULL(){
        txtmadinhdanh.setText("");
        txthoten.setText("");
        txtbidanh.setText("");
        txtngaysinh.setText("");
        txtnoisinh.setText("");
        txtnguyenquan.setText("");
        txtdantoc.setText("");
        txtnghenghiep.setText("");
        txtnoilamviec.setText("");
        txtcmnd.setText("");
        txtngaycap.setText("");
        txtnoicap.setText("");
        txtquanhe.setText("");
        txtdiachicu.setText("");
        txtngaydkthuongtru.setText("");
        txtcmnd.setEditable(true);
        txtdiachicu.setEditable(true);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        txtngaychuyendi.setVisible(false);
        txtnoichuyen.setVisible(false);
        txtghichu.setVisible(false);
    }
    
   private void setLock(){
        txtmadinhdanh.setEditable(false);
        txthoten.setEditable(false);
        txtbidanh.setEditable(false);
        txtngaysinh.setEditable(false);
        txtnoisinh.setEditable(false);
        txtnguyenquan.setEditable(false);
        txtdantoc.setEditable(false);
        txtnghenghiep.setEditable(false);
        txtnoilamviec.setEditable(false);
        txtcmnd.setEditable(false);
        txtngaycap.setEditable(false);
        txtnoicap.setEditable(false);
        txtquanhe.setEditable(false);
        txtdiachicu.setEditable(false);
        txtngaydkthuongtru.setEditable(false);
        ghichucombobox.setEnabled(false);
   }
    
   private void setUnlock(){
        txtmadinhdanh.setEditable(true);
        txthoten.setEditable(true);
        txtbidanh.setEditable(true);
        txtngaysinh.setEditable(true);
        txtnoisinh.setEditable(true);
        txtnguyenquan.setEditable(true);
        txtdantoc.setEditable(true);
        txtnghenghiep.setEditable(true);
        txtnoilamviec.setEditable(true);
        txtcmnd.setEditable(true);
        txtngaycap.setEditable(true);
        txtnoicap.setEditable(true);
        txtquanhe.setEditable(true);
        txtdiachicu.setEditable(true);
        txtngaydkthuongtru.setEditable(true);
        ghichucombobox.setEnabled(true);
   }
   
    public ThemNhankhauFR() {
        initComponents();
        txtsohokhau.setText(nhankhaudao.id);
        txttenchuho.setText(nhankhaudao.ten);
        txtsohokhau.setEditable(false);
        txttenchuho.setEditable(false);
        setLock();
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        txtngaychuyendi.setVisible(false);
        txtnoichuyen.setVisible(false);
        txtghichu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtmadinhdanh = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtbidanh = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtnoisinh = new javax.swing.JTextField();
        txtnguyenquan = new javax.swing.JTextField();
        txtdantoc = new javax.swing.JTextField();
        txtnghenghiep = new javax.swing.JTextField();
        txtnoilamviec = new javax.swing.JTextField();
        txtcmnd = new javax.swing.JTextField();
        txtngaycap = new javax.swing.JTextField();
        txtnoicap = new javax.swing.JTextField();
        txtquanhe = new javax.swing.JTextField();
        txtdiachicu = new javax.swing.JTextField();
        txtngaydkthuongtru = new javax.swing.JTextField();
        thembutton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtsohokhau = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txttenchuho = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        doituongthemcombobox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        ghichucombobox = new javax.swing.JComboBox<>();
        txtghichu = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtngaychuyendi = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtnoichuyen = new javax.swing.JTextField();
        quaylaibutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(502, 250));

        jLabel1.setText("Mã định danh:");

        jLabel2.setText("Họ tên:");

        jLabel3.setText("Bí danh:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("Nơi sinh:");

        jLabel6.setText("Nguyên quán:");

        jLabel7.setText("Dân tộc:");

        jLabel8.setText("Nghề nghiệp:");

        jLabel9.setText("Nơi làm việc:");

        jLabel10.setText("Số CMND:");

        jLabel11.setText("Ngày cấp:");

        jLabel12.setText("Nơi cấp:");

        jLabel13.setText("Quan hệ với chủ hộ:");

        jLabel14.setText("Địa chỉ thường trú cũ:");

        jLabel15.setText("Ngày đăng kí thường trú:");

        txtnoisinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoisinhActionPerformed(evt);
            }
        });

        txtnguyenquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnguyenquanActionPerformed(evt);
            }
        });

        txtquanhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquanheActionPerformed(evt);
            }
        });

        txtngaydkthuongtru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaydkthuongtruActionPerformed(evt);
            }
        });

        thembutton.setText("Thêm");
        thembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thembuttonActionPerformed(evt);
            }
        });

        jLabel16.setText("Số hộ khẩu:");

        jLabel17.setText("Chủ hộ:");

        jLabel18.setText("Đối tượng thêm:");

        doituongthemcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trẻ em", "Đối tượng khác" }));
        doituongthemcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doituongthemcomboboxActionPerformed(evt);
            }
        });

        jLabel19.setText("Ghi chú:");

        ghichucombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuyển đi nơi khác", "Qua đời", "Khác", "Không có" }));
        ghichucombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghichucomboboxActionPerformed(evt);
            }
        });

        jLabel20.setText("Ghi chú khác:");

        jLabel21.setText("Ngày chuyển đi:");

        jLabel22.setText("Nơi chuyển:");

        quaylaibutton.setText("Quay lại");
        quaylaibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylaibuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtnguyenquan, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(txtdantoc)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtnoisinh))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtmadinhdanh, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(txthoten)
                                        .addComponent(txtbidanh, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtngaysinh)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtngaychuyendi, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(txtnoichuyen)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtdiachicu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel10))
                                            .addComponent(jLabel9))
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtcmnd)
                                        .addComponent(txtnghenghiep)
                                        .addComponent(txtnoilamviec)
                                        .addComponent(txtquanhe, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtnoicap)
                                        .addComponent(txtngaycap, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(46, 46, 46))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtngaydkthuongtru, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtsohokhau, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(79, 79, 79)
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txttenchuho, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(doituongthemcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ghichucombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel20))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(thembutton)
                .addGap(118, 118, 118)
                .addComponent(quaylaibutton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtsohokhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txttenchuho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(doituongthemcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmadinhdanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtquanhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtnghenghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtbidanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnoilamviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(txtcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnoisinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtngaycap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtnguyenquan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtdantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtdiachicu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaydkthuongtru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnoicap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ghichucombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngaychuyendi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtnoichuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thembutton)
                    .addComponent(quaylaibutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnguyenquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnguyenquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnguyenquanActionPerformed

    private void txtnoisinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoisinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoisinhActionPerformed

    private void setNhankhau (){
         nk.setSohokhau(nhankhaudao.id);
         nk.setMadinhdanh(txtmadinhdanh.getText());
         nk.setHoten(txthoten.getText());
         nk.setBidanh(txtbidanh.getText());
         try {
                nk.setNgaysinh(fmt.parse(txtngaysinh.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(ThemNhankhauFR.class.getName()).log(Level.SEVERE, null, ex);
            }
        nk.setNoisinh(txtnoisinh.getText());
        nk.setNguyenquan(txtnguyenquan.getText());
        nk.setDantoc(txtdantoc.getText());
        nk.setCmnd(txtcmnd.getText());
        try {
                nk.setNgaycap(fmt.parse(txtngaycap.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(ThemNhankhauFR.class.getName()).log(Level.SEVERE, null, ex);
            }
        nk.setNoicap(txtnoicap.getText());
        nk.setQuanhe(txtquanhe.getText());
        nk.setDiachicu(txtdiachicu.getText());
        try {
                nk.setNgaydkthuongtru(fmt.parse(txtngaydkthuongtru.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(ThemNhankhauFR.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void setGhichu(){
        String selectedRow=(String) ghichucombobox.getSelectedItem();
        if(selectedRow.equals("Chuyển đi nơi khác")){
            nk.setGhichu("Chuyển đi nơi khác");
            nk.setNoichuyen(txtnoichuyen.getText());
            try {
                nk.setNgaychuyendi(fmt.parse(txtngaychuyendi.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(ThemNhankhauFR.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(selectedRow.equals("Khác")){
            nk.setGhichu(txtghichu.getText());
            nk.setNoichuyen("");
            try {
                    nk.setNgaychuyendi(fmt.parse("00/00/0000"));
                } catch (ParseException ex) {
                    Logger.getLogger(ThemNhankhauFR.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else if(selectedRow.equals("Qua đời")){
            nk.setGhichu("Qua đời");
            nk.setNoichuyen("");
            try {
                    nk.setNgaychuyendi(fmt.parse("00/00/0000"));
                } catch (ParseException ex) {
                    Logger.getLogger(ThemNhankhauFR.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else if(selectedRow.equals("Không có")){
            nk.setGhichu("");
            nk.setNoichuyen("");
            try {
                    nk.setNgaychuyendi(fmt.parse("00/00/0000"));
                } catch (ParseException ex) {
                    Logger.getLogger(ThemNhankhauFR.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
    
    private void thembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thembuttonActionPerformed
        // TODO add your handling code here:
        try{

            String selectedRow=(String)doituongthemcombobox.getSelectedItem();
            if(selectedRow.equals("Trẻ em")){
                setNhankhau();
                nk.setNghenghiep("");
                nk.setNoilamviec("");
                setGhichu();
            }else if(selectedRow.equals("Đối tượng khác")){
                setNhankhau();
                nk.setNghenghiep(txtnghenghiep.getText());
                nk.setNoilamviec(txtnoilamviec.getText());
                setGhichu();
            }
            
            if (nhankhaudao.themnhankhau(nk) == 1) {
                JOptionPane.showMessageDialog(this," Đã thêm ! ");
            } else {
                JOptionPane.showMessageDialog(this, " Thêm thất bại ! ");
            }
            //setNULL();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, " Thêm thất bại ! "+ex.toString());
        }
    }//GEN-LAST:event_thembuttonActionPerformed

    private void txtngaydkthuongtruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaydkthuongtruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaydkthuongtruActionPerformed

    private void txtquanheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquanheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquanheActionPerformed

    private void doituongthemcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doituongthemcomboboxActionPerformed
        // TODO add your handling code here:
        String selectedRow=(String)doituongthemcombobox.getSelectedItem();
        if(selectedRow.equals("Trẻ em")){
            setUnlock();
            txtnghenghiep.setText("NULL");
            txtnoilamviec.setText("NULL");
            txtcmnd.setText("mới sinh");
            txtdiachicu.setText("mới sinh");
            txtnghenghiep.setEditable(false);
            txtnoilamviec.setEditable(false);
            txtcmnd.setEditable(false);
            txtdiachicu.setEditable(false);
        }else if(selectedRow.equals("Đối tượng khác")){
            setUnlock();
            txtnghenghiep.setText("");
            txtnoilamviec.setText("");
            txtcmnd.setText("");
            txtdiachicu.setText("");
        }
    }//GEN-LAST:event_doituongthemcomboboxActionPerformed

    private void ghichucomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghichucomboboxActionPerformed
        // TODO add your handling code here:
        String selectedRow=(String) ghichucombobox.getSelectedItem();
        if(selectedRow.equals("Chuyển đi nơi khác")){
            jLabel20.setVisible(false);
            jLabel21.setVisible(true);
            jLabel22.setVisible(true);
            txtngaychuyendi.setVisible(true);
            txtnoichuyen.setVisible(true);
            txtghichu.setVisible(false);
        }else if(selectedRow.equals("Khác")){
            jLabel20.setVisible(true);
            jLabel21.setVisible(false);
            jLabel22.setVisible(false);
            txtghichu.setVisible(true);
            txtngaychuyendi.setVisible(false);
            txtnoichuyen.setVisible(false);
        }else if((selectedRow.equals("Qua đời"))||(selectedRow.equals("Không có"))){
            jLabel20.setVisible(false);
            jLabel21.setVisible(false);
            jLabel22.setVisible(false);
            txtghichu.setVisible(false);
            txtngaychuyendi.setVisible(false);
            txtnoichuyen.setVisible(false);
        }
    }//GEN-LAST:event_ghichucomboboxActionPerformed

    private void quaylaibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylaibuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quaylaibuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNhankhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNhankhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNhankhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNhankhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNhankhauFR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> doituongthemcombobox;
    private javax.swing.JComboBox<String> ghichucombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton quaylaibutton;
    private javax.swing.JButton thembutton;
    private javax.swing.JTextField txtbidanh;
    private javax.swing.JTextField txtcmnd;
    private javax.swing.JTextField txtdantoc;
    private javax.swing.JTextField txtdiachicu;
    private javax.swing.JTextField txtghichu;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmadinhdanh;
    private javax.swing.JTextField txtngaycap;
    private javax.swing.JTextField txtngaychuyendi;
    private javax.swing.JTextField txtngaydkthuongtru;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtnghenghiep;
    private javax.swing.JTextField txtnguyenquan;
    private javax.swing.JTextField txtnoicap;
    private javax.swing.JTextField txtnoichuyen;
    private javax.swing.JTextField txtnoilamviec;
    private javax.swing.JTextField txtnoisinh;
    private javax.swing.JTextField txtquanhe;
    private javax.swing.JTextField txtsohokhau;
    private javax.swing.JTextField txttenchuho;
    // End of variables declaration//GEN-END:variables
}
